gonpush/config/routes.rb
Rails.application.routes.draw do
 
  resources :socail_accounts
  resources :social_channels
  resources :cases
  resources :reports
  get 'sessions/new'
  resources :tasks
  resources :orders
  resources :tags
  resources :schedules
  resources :areas
  resources :comments
  resources :contracts
  resources :posts
  resources :flows
  resources :social_accounts
  resources :categories
  resources :creator_exts
  resources :metrics
  resources :creator_metrics
  resources :services
  resources :users
  resources :campaigns
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login' , to:'sessions#create'
  get '/logout' , to: 'sessions#destrory'
  get '/getOrder', to: 'orders#showOrder'
  post '/updateSchedule', to: 'orders#updateSchedule'
  delete "orders/destroy/:id" => "orders#destroy"
  delete "reports/destroy/:id" => "reports#destroy"
  delete "cases/destroy/:id" => "cases#destroy"
  delete "services/destroy/:id" => "services#destroy"
  post  '/getservice',to:'sessions#getservices'
  get '/inviterequired', to: 'users#inviterequired'
  post '/saveinviterequired' , to:'users#saveinviterequired'
  get '/updatepassword', to: 'users#updatepassword'
  post '/savepassword' , to:'users#savepassword'
  get '/userinfo', to: 'users#userinfo'
  post '/saveuserinfo' , to:'users#saveuserinfo'

end

gonpush/app/models/area.rb
class Area < ApplicationRecord
end

gonpush/app/models/campaign.rb
class Campaign < ApplicationRecord
	validates_presence_of :name, :message =>"项目名称不能为空" 
	validates_presence_of :description, :message =>"关键信息不能为空" 
	validates_presence_of :budget, :message =>"预算不能为空" 
 def new
    @campaign = Campaign.new
    @users = User.all
  end
end

gonpush/app/models/case.rb
class Case < ApplicationRecord
end

gonpush/app/models/category.rb
class Category < ApplicationRecord
end

gonpush/app/models/comment.rb
class Comment < ApplicationRecord
end

gonpush/app/models/contract.rb
class Contract < ApplicationRecord
end

gonpush/app/models/creator_ext.rb
class CreatorExt < ApplicationRecord
end

gonpush/app/models/flow.rb
class Flow < ApplicationRecord
end

gonpush/app/models/metric.rb
class Metric < ApplicationRecord
end

gonpush/app/models/order.rb
class Order < ApplicationRecord
end

gonpush/app/models/post.rb
class Post < ApplicationRecord
end

gonpush/app/models/report.rb
class Report < ApplicationRecord
end

gonpush/app/models/schedule.rb
class Schedule < ApplicationRecord
end

gonpush/app/models/service.rb
class Service < ApplicationRecord
end

gonpush/app/models/tag.rb
class Tag < ApplicationRecord
end

gonpush/app/models/task.rb
class Task < ApplicationRecord
end

gonpush/app/models/user.rb
class User < ApplicationRecord
def getcreator
	@users = User.all
end
def authenticate(submitted_password)
  return self.has_password?(submitted_password)
end


end

gonpush/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:campaign_id, :flow_name, :flow_order, :starts_on, :ends_on, :workdays, :status, :post_id)
    end
end

gonpush/app/helpers/areas_helper.rb
module AreasHelper
end

gonpush/app/helpers/cases_helper.rb
module CasesHelper
end

gonpush/app/helpers/flows_helper.rb
module FlowsHelper
end

gonpush/app/helpers/schedules_helper.rb
module SchedulesHelper
end

gonpush/app/helpers/tags_helper.rb
module TagsHelper
end

gonpush/app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :campaign_id %>
    <%= form.number_field :campaign_id %>
  </div>

  <div class="field">
    <%= form.label :flow_name %>
    <%= form.number_field :flow_name %>
  </div>

  <div class="field">
    <%= form.label :flow_order %>
    <%= form.number_field :flow_order %>
  </div>

  <div class="field">
    <%= form.label :starts_on %>
    <%= form.datetime_select :starts_on %>
  </div>

  <div class="field">
    <%= form.label :ends_on %>
    <%= form.datetime_select :ends_on %>
  </div>

  <div class="field">
    <%= form.label :workdays %>
    <%= form.number_field :workdays %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.number_field :post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

gonpush/app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

gonpush/app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Campaign</th>
      <th>Flow name</th>
      <th>Flow order</th>
      <th>Starts on</th>
      <th>Ends on</th>
      <th>Workdays</th>
      <th>Status</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.campaign_id %></td>
        <td><%= schedule.flow_name %></td>
        <td><%= schedule.flow_order %></td>
        <td><%= schedule.starts_on %></td>
        <td><%= schedule.ends_on %></td>
        <td><%= schedule.workdays %></td>
        <td><%= schedule.status %></td>
        <td><%= schedule.post_id %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

gonpush/app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

gonpush/app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Campaign:</strong>
  <%= @schedule.campaign_id %>
</p>

<p>
  <strong>Flow name:</strong>
  <%= @schedule.flow_name %>
</p>

<p>
  <strong>Flow order:</strong>
  <%= @schedule.flow_order %>
</p>

<p>
  <strong>Starts on:</strong>
  <%= @schedule.starts_on %>
</p>

<p>
  <strong>Ends on:</strong>
  <%= @schedule.ends_on %>
</p>

<p>
  <strong>Workdays:</strong>
  <%= @schedule.workdays %>
</p>

<p>
  <strong>Status:</strong>
  <%= @schedule.status %>
</p>

<p>
  <strong>Post:</strong>
  <%= @schedule.post_id %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>