gonpush/config/routes.rb
Rails.application.routes.draw do
 
  resources :socail_accounts
  resources :social_channels
  resources :cases
  resources :reports
  get 'sessions/new'
  resources :tasks
  resources :orders
  resources :tags
  resources :schedules
  resources :areas
  resources :comments
  resources :contracts
  resources :posts
  resources :flows
  resources :social_accounts
  resources :categories
  resources :creator_exts
  resources :metrics
  resources :creator_metrics
  resources :services
  resources :users
  resources :campaigns
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login' , to:'sessions#create'
  get '/logout' , to: 'sessions#destrory'
  get '/getOrder', to: 'orders#showOrder'
  post '/updateSchedule', to: 'orders#updateSchedule'
  delete "orders/destroy/:id" => "orders#destroy"
  delete "reports/destroy/:id" => "reports#destroy"
  delete "cases/destroy/:id" => "cases#destroy"
  delete "services/destroy/:id" => "services#destroy"
  post  '/getservice',to:'sessions#getservices'
  get '/inviterequired', to: 'users#inviterequired'
  post '/saveinviterequired' , to:'users#saveinviterequired'
  get '/updatepassword', to: 'users#updatepassword'
  post '/savepassword' , to:'users#savepassword'
  get '/userinfo', to: 'users#userinfo'
  post '/saveuserinfo' , to:'users#saveuserinfo'

end

gonpush/app/models/area.rb
class Area < ApplicationRecord
end

gonpush/app/models/campaign.rb
class Campaign < ApplicationRecord
	validates_presence_of :name, :message =>"项目名称不能为空" 
	validates_presence_of :description, :message =>"关键信息不能为空" 
	validates_presence_of :budget, :message =>"预算不能为空" 
 def new
    @campaign = Campaign.new
    @users = User.all
  end
end

gonpush/app/models/case.rb
class Case < ApplicationRecord
end

gonpush/app/models/category.rb
class Category < ApplicationRecord
end

gonpush/app/models/comment.rb
class Comment < ApplicationRecord
end

gonpush/app/models/contract.rb
class Contract < ApplicationRecord
end

gonpush/app/models/creator_ext.rb
class CreatorExt < ApplicationRecord
end

gonpush/app/models/flow.rb
class Flow < ApplicationRecord
end

gonpush/app/models/metric.rb
class Metric < ApplicationRecord
end

gonpush/app/models/order.rb
class Order < ApplicationRecord
end

gonpush/app/models/post.rb
class Post < ApplicationRecord
end

gonpush/app/models/report.rb
class Report < ApplicationRecord
end

gonpush/app/models/schedule.rb
class Schedule < ApplicationRecord
end

gonpush/app/models/service.rb
class Service < ApplicationRecord
end

gonpush/app/models/tag.rb
class Tag < ApplicationRecord
end

gonpush/app/models/task.rb
class Task < ApplicationRecord
end

gonpush/app/models/user.rb
class User < ApplicationRecord
def getcreator
	@users = User.all
end
def authenticate(submitted_password)
  return self.has_password?(submitted_password)
end


end

gonpush/app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:areaName, :area_level, :area_sequence, :parent_id)
    end
end

gonpush/app/helpers/areas_helper.rb
module AreasHelper
end

gonpush/app/helpers/cases_helper.rb
module CasesHelper
end

gonpush/app/helpers/flows_helper.rb
module FlowsHelper
end

gonpush/app/helpers/posts_helper.rb
module PostsHelper
end

gonpush/app/helpers/tags_helper.rb
module TagsHelper
end

gonpush/app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :areaName %>
    <%= form.text_field :areaName %>
  </div>

  <div class="field">
    <%= form.label :area_level %>
    <%= form.number_field :area_level %>
  </div>

  <div class="field">
    <%= form.label :area_sequence %>
    <%= form.number_field :area_sequence %>
  </div>

  <div class="field">
    <%= form.label :parent_id %>
    <%= form.number_field :parent_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

gonpush/app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

gonpush/app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Areas</h1>

<table>
  <thead>
    <tr>
      <th>Areaname</th>
      <th>Area level</th>
      <th>Area sequence</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.areaName %></td>
        <td><%= area.area_level %></td>
        <td><%= area.area_sequence %></td>
        <td><%= area.parent_id %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

gonpush/app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', areas_path %>

gonpush/app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Areaname:</strong>
  <%= @area.areaName %>
</p>

<p>
  <strong>Area level:</strong>
  <%= @area.area_level %>
</p>

<p>
  <strong>Area sequence:</strong>
  <%= @area.area_sequence %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @area.parent_id %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>