gonpush/config/routes.rb
Rails.application.routes.draw do
 
  resources :socail_accounts
  resources :social_channels
  resources :cases
  resources :reports
  get 'sessions/new'
  resources :tasks
  resources :orders
  resources :tags
  resources :schedules
  resources :areas
  resources :comments
  resources :contracts
  resources :posts
  resources :flows
  resources :social_accounts
  resources :categories
  resources :creator_exts
  resources :metrics
  resources :creator_metrics
  resources :services
  resources :users
  resources :campaigns
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login' , to:'sessions#create'
  get '/logout' , to: 'sessions#destrory'
  get '/getOrder', to: 'orders#showOrder'
  post '/updateSchedule', to: 'orders#updateSchedule'
  delete "orders/destroy/:id" => "orders#destroy"
  delete "reports/destroy/:id" => "reports#destroy"
  delete "cases/destroy/:id" => "cases#destroy"
  delete "services/destroy/:id" => "services#destroy"
  post  '/getservice',to:'sessions#getservices'
  get '/inviterequired', to: 'users#inviterequired'
  post '/saveinviterequired' , to:'users#saveinviterequired'
  get '/updatepassword', to: 'users#updatepassword'
  post '/savepassword' , to:'users#savepassword'
  get '/userinfo', to: 'users#userinfo'
  post '/saveuserinfo' , to:'users#saveuserinfo'

end

gonpush/app/models/area.rb
class Area < ApplicationRecord
end

gonpush/app/models/campaign.rb
class Campaign < ApplicationRecord
	validates_presence_of :name, :message =>"项目名称不能为空" 
	validates_presence_of :description, :message =>"关键信息不能为空" 
	validates_presence_of :budget, :message =>"预算不能为空" 
 def new
    @campaign = Campaign.new
    @users = User.all
  end
end

gonpush/app/models/case.rb
class Case < ApplicationRecord
end

gonpush/app/models/category.rb
class Category < ApplicationRecord
end

gonpush/app/models/comment.rb
class Comment < ApplicationRecord
end

gonpush/app/models/contract.rb
class Contract < ApplicationRecord
end

gonpush/app/models/creator_ext.rb
class CreatorExt < ApplicationRecord
end

gonpush/app/models/flow.rb
class Flow < ApplicationRecord
end

gonpush/app/models/metric.rb
class Metric < ApplicationRecord
end

gonpush/app/models/order.rb
class Order < ApplicationRecord
end

gonpush/app/models/post.rb
class Post < ApplicationRecord
end

gonpush/app/models/report.rb
class Report < ApplicationRecord
end

gonpush/app/models/schedule.rb
class Schedule < ApplicationRecord
end

gonpush/app/models/service.rb
class Service < ApplicationRecord
end

gonpush/app/models/social_channel.rb
class SocialChannel < ApplicationRecord
end

gonpush/app/models/tag.rb
class Tag < ApplicationRecord
end

gonpush/app/models/task.rb
class Task < ApplicationRecord
end

gonpush/app/models/user.rb
class User < ApplicationRecord
def getcreator
	@users = User.all
end
def authenticate(submitted_password)
  return self.has_password?(submitted_password)
end


end

gonpush/app/controllers/social_channels_controller.rb
class SocialChannelsController < ApplicationController
  before_action :set_social_channel, only: [:show, :edit, :update, :destroy]

  # GET /social_channels
  # GET /social_channels.json
  def index
    @social_channels = SocialChannel.all
  end

  # GET /social_channels/1
  # GET /social_channels/1.json
  def show
  end

  # GET /social_channels/new
  def new
    @social_channel = SocialChannel.new
  end

  # GET /social_channels/1/edit
  def edit
  end

  # POST /social_channels
  # POST /social_channels.json
  def create
    @social_channel = SocialChannel.new(social_channel_params)

    respond_to do |format|
      if @social_channel.save
        format.html { redirect_to @social_channel, notice: 'Social channel was successfully created.' }
        format.json { render :show, status: :created, location: @social_channel }
      else
        format.html { render :new }
        format.json { render json: @social_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /social_channels/1
  # PATCH/PUT /social_channels/1.json
  def update
    respond_to do |format|
      if @social_channel.update(social_channel_params)
        format.html { redirect_to @social_channel, notice: 'Social channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @social_channel }
      else
        format.html { render :edit }
        format.json { render json: @social_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /social_channels/1
  # DELETE /social_channels/1.json
  def destroy
    @social_channel.destroy
    respond_to do |format|
      format.html { redirect_to social_channels_url, notice: 'Social channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_social_channel
      @social_channel = SocialChannel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def social_channel_params
      params.require(:social_channel).permit(:name)
    end
end

gonpush/app/helpers/areas_helper.rb
module AreasHelper
end

gonpush/app/helpers/cases_helper.rb
module CasesHelper
end

gonpush/app/helpers/social_channels_helper.rb
module SocialChannelsHelper
end

gonpush/app/helpers/tags_helper.rb
module TagsHelper
end

gonpush/app/views/social_channels/_form.html.erb
<%= form_with(model: social_channel, local: true) do |form| %>
  <% if social_channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(social_channel.errors.count, "error") %> prohibited this social_channel from being saved:</h2>

      <ul>
      <% social_channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

gonpush/app/views/social_channels/edit.html.erb
<h1>Editing Social Channel</h1>

<%= render 'form', social_channel: @social_channel %>

<%= link_to 'Show', @social_channel %> |
<%= link_to 'Back', social_channels_path %>

gonpush/app/views/social_channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Social Channels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @social_channels.each do |social_channel| %>
      <tr>
        <td><%= social_channel.name %></td>
        <td><%= link_to 'Show', social_channel %></td>
        <td><%= link_to 'Edit', edit_social_channel_path(social_channel) %></td>
        <td><%= link_to 'Destroy', social_channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Social Channel', new_social_channel_path %>

gonpush/app/views/social_channels/new.html.erb
<h1>New Social Channel</h1>

<%= render 'form', social_channel: @social_channel %>

<%= link_to 'Back', social_channels_path %>

gonpush/app/views/social_channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @social_channel.name %>
</p>

<%= link_to 'Edit', edit_social_channel_path(@social_channel) %> |
<%= link_to 'Back', social_channels_path %>