gonpush/config/routes.rb
Rails.application.routes.draw do
 
  resources :socail_accounts
  resources :social_channels
  resources :cases
  resources :reports
  get 'sessions/new'
  resources :tasks
  resources :orders
  resources :tags
  resources :schedules
  resources :areas
  resources :comments
  resources :contracts
  resources :posts
  resources :flows
  resources :social_accounts
  resources :categories
  resources :creator_exts
  resources :metrics
  resources :creator_metrics
  resources :services
  resources :users
  resources :campaigns
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login' , to:'sessions#create'
  get '/logout' , to: 'sessions#destrory'
  get '/getOrder', to: 'orders#showOrder'
  post '/updateSchedule', to: 'orders#updateSchedule'
  delete "orders/destroy/:id" => "orders#destroy"
  delete "reports/destroy/:id" => "reports#destroy"
  delete "cases/destroy/:id" => "cases#destroy"
  delete "services/destroy/:id" => "services#destroy"
  post  '/getservice',to:'sessions#getservices'
  get '/inviterequired', to: 'users#inviterequired'
  post '/saveinviterequired' , to:'users#saveinviterequired'
  get '/updatepassword', to: 'users#updatepassword'
  post '/savepassword' , to:'users#savepassword'
  get '/userinfo', to: 'users#userinfo'
  post '/saveuserinfo' , to:'users#saveuserinfo'

end

gonpush/app/models/area.rb
class Area < ApplicationRecord
end

gonpush/app/models/campaign.rb
class Campaign < ApplicationRecord
	validates_presence_of :name, :message =>"项目名称不能为空" 
	validates_presence_of :description, :message =>"关键信息不能为空" 
	validates_presence_of :budget, :message =>"预算不能为空" 
 def new
    @campaign = Campaign.new
    @users = User.all
  end
end

gonpush/app/models/case.rb
class Case < ApplicationRecord
end

gonpush/app/models/category.rb
class Category < ApplicationRecord
end

gonpush/app/models/comment.rb
class Comment < ApplicationRecord
end

gonpush/app/models/contract.rb
class Contract < ApplicationRecord
end

gonpush/app/models/creator_ext.rb
class CreatorExt < ApplicationRecord
end

gonpush/app/models/flow.rb
class Flow < ApplicationRecord
end

gonpush/app/models/metric.rb
class Metric < ApplicationRecord
end

gonpush/app/models/order.rb
class Order < ApplicationRecord
end

gonpush/app/models/post.rb
class Post < ApplicationRecord
end

gonpush/app/models/report.rb
class Report < ApplicationRecord
end

gonpush/app/models/schedule.rb
class Schedule < ApplicationRecord
end

gonpush/app/models/service.rb
class Service < ApplicationRecord
end

gonpush/app/models/tag.rb
class Tag < ApplicationRecord
end

gonpush/app/models/task.rb
class Task < ApplicationRecord
end

gonpush/app/models/user.rb
class User < ApplicationRecord
def getcreator
	@users = User.all
end
def authenticate(submitted_password)
  return self.has_password?(submitted_password)
end


end

gonpush/app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  before_action :set_metric, only: [:show, :edit, :update, :destroy]

  # GET /metrics
  # GET /metrics.json
  def index
    @metrics = Metric.all
  end

  # GET /metrics/1
  # GET /metrics/1.json
  def show
  end

  # GET /metrics/new
  def new
    @metric = Metric.new
  end

  # GET /metrics/1/edit
  def edit
  end

  # POST /metrics
  # POST /metrics.json
  def create
    @metric = Metric.new(metric_params)

    respond_to do |format|
      if @metric.save
        format.html { redirect_to @metric, notice: 'Metric was successfully created.' }
        format.json { render :show, status: :created, location: @metric }
      else
        format.html { render :new }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metrics/1
  # PATCH/PUT /metrics/1.json
  def update
    respond_to do |format|
      if @metric.update(metric_params)
        format.html { redirect_to @metric, notice: 'Metric was successfully updated.' }
        format.json { render :show, status: :ok, location: @metric }
      else
        format.html { render :edit }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metrics/1
  # DELETE /metrics/1.json
  def destroy
    @metric.destroy
    respond_to do |format|
      format.html { redirect_to metrics_url, notice: 'Metric was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metric
      @metric = Metric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def metric_params
      params.require(:metric).permit(:name)
    end
end

gonpush/app/helpers/areas_helper.rb
module AreasHelper
end

gonpush/app/helpers/cases_helper.rb
module CasesHelper
end

gonpush/app/helpers/flows_helper.rb
module FlowsHelper
end

gonpush/app/helpers/metrics_helper.rb
module MetricsHelper
end

gonpush/app/helpers/tags_helper.rb
module TagsHelper
end

gonpush/app/views/metrics/_form.html.erb
<%= form_with(model: metric, local: true) do |form| %>
  <% if metric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(metric.errors.count, "error") %> prohibited this metric from being saved:</h2>

      <ul>
      <% metric.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

gonpush/app/views/metrics/edit.html.erb
<h1>Editing Metric</h1>

<%= render 'form', metric: @metric %>

<%= link_to 'Show', @metric %> |
<%= link_to 'Back', metrics_path %>

gonpush/app/views/metrics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Metrics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @metrics.each do |metric| %>
      <tr>
        <td><%= metric.name %></td>
        <td><%= link_to 'Show', metric %></td>
        <td><%= link_to 'Edit', edit_metric_path(metric) %></td>
        <td><%= link_to 'Destroy', metric, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Metric', new_metric_path %>

gonpush/app/views/metrics/new.html.erb
<h1>New Metric</h1>

<%= render 'form', metric: @metric %>

<%= link_to 'Back', metrics_path %>

gonpush/app/views/metrics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @metric.name %>
</p>

<%= link_to 'Edit', edit_metric_path(@metric) %> |
<%= link_to 'Back', metrics_path %>